name: Deploy Next.js to Webuzo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 103.91.186.61
          username: houselink360
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 2244
          script: |
            set -e

            git config --global --add safe.directory /home/houselink360/nextjs

            cd /home/houselink360/nextjs

            echo "Resetting local changes..."
            git reset --hard

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            npm install
            npm install sharp

            echo "Building project..."
            npm run build

            echo "Fixing permissions for web server..."
            chmod -R 755 .next public

            echo "Restarting app..."
            pm2 delete nextjs-app || true
            pm2 delete houselink-nextjs || true
            pm2 start npm --name "houselink-nextjs" -- start

            echo "Deployment complete"